### PR TITLE
Be nicer when a dashboard is deleted from grafana

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Review by radeksimko — COMMENTED** [review]
This looks reasonable (assuming there is no cleaner way to catch 404 other than string matching it).

Just one question - do you mind adding a test for this? We have some tests for such behaviour elsewhere, e.g. https://github.com/terraform-providers/terraform-provider-aws/blob/b8d4e1570fc43a2acee6b6e47f63c9db6b067fa2/aws/resource_aws_cloudwatch_log_stream_test.go#L33-L52

**Comment by roidelapluie** [comment]
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-grafana	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccAlertNotification_basic
request to  http://admin:admin@127.0.0.1:3000/api/alert-notifications with body data {"name":"terraform-acc-test","type":"email","isDefault":false,"settings":{"addresses":"foo@bar.test","uploadImage":"false"}}
request to  http://admin:admin@127.0.0.1:3000/api/alert-notifications/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/alert-notifications/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/alert-notifications/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/alert-notifications/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/alert-notifications/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/alert-notifications/4 with no body data
--- FAIL: TestAccAlertNotification_basic (0.22s)
	testing.go:499: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Check failed: alert-notification still exists
		
		State: <no state>
=== RUN   TestAccDashboard_basic
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db with body data {"dashboard":{"title":"Terraform Acceptance Test","version":0},"overwrite":false}
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
--- PASS: TestAccDashboard_basic (0.23s)
=== RUN   TestAccDashboard_disappear
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db with body data {"dashboard":{"title":"Terraform Acceptance Test","version":0},"overwrite":false}
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
request to  http://admin:admin@127.0.0.1:3000/api/dashboards/db/terraform-acceptance-test with no body data
--- PASS: TestAccDashboard_disappear (0.19s)
=== RUN   TestAccDataSource_basic
request to  http://admin:admin@127.0.0.1:3000/api/datasources with body data {"name":"terraform-acc-test","type":"influxdb","url":"http://terraform-acc-test.invalid/","access":"proxy","database":"terraform-acc-test","user":"terraform_user","password":"terraform_password","isDefault":false,"basicAuth":false}
request to  http://admin:admin@127.0.0.1:3000/api/datasources/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/datasources/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/datasources/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/datasources/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/datasources/4 with no body data
request to  http://admin:admin@127.0.0.1:3000/api/datasources/4 with no body data
--- PASS: TestAccDataSource_basic (0.22s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-grafana/grafana	0.872s
```

**Comment by roidelapluie** [comment]
Failure is unrelated

**Review by radeksimko — APPROVED** [review]
LGTM 👍  Thanks.

**Pull request merged**
