### PR TITLE
2075-terraform

### PR DESCRIPTION
**Pull request by JohnnyK-Grafana**
[fixes 2075](https://github.com/grafana/slo/issues/2075)

### CODE REVIEW

**Review by ellisda — APPROVED** [review]
LGTM (not that my approval is of any value here)

**Comment by JohnnyK-Grafana** [comment]
hey @jdbaldry - could you take a peek at this and let me know where things went rotten? thanks!

**Comment by jdbaldry** [comment]
I _can_ dig into this but it's probably best for a repository maintainer as they have the context for how the tests behave.

**Comment by jdbaldry** [comment]
To help, you may want to provide more context in your PR subject and description to explain the purpose of the change so that can be compared to the patch that achieves that purpose

**Pull request closed without merging**
