### PR TITLE
Add missing Sentry attributes

### LINKED ISSUE #346: Add Support for Sentry Plugin
https://grafana.com/grafana/plugins/grafana-sentry-datasource/

the `json_data` arg is missing `org_slug`
the `secure_json_data` is missing `auth_token`

### PR DESCRIPTION
**Pull request by inkel**
Fixes #346

### CODE REVIEW

**Comment by inkel** [comment]
🤔 well, it didn't like `orgSlug` and `authToken` because _field name may only contain lowercase alphanumeric characters & underscores_.

**Comment by julienduchesne** [comment]
> 🤔 well, it didn't like `orgSlug` and `authToken` because _field name may only contain lowercase alphanumeric characters & underscores_.

They should be `org_slug` and `auth_token`

**Comment by inkel** [comment]
Yeah, I'm about to make the change.

**Comment by inkel** [comment]
This is blocked until we [merge](https://github.com/grafana/grafana-api-golang-client/pull/57) and release the Go client.

**Review by julienduchesne — APPROVED** [review]

**Comment by inkel** [comment]
This now depends on https://github.com/grafana/grafana-api-golang-client/pull/58 because we've found an issue on how the provider treats the `url` attribute.

**Pull request merged**
