### PR TITLE
add data_source_library_panel

### PR DESCRIPTION
**Pull request by justinTM**

### CODE REVIEW

**Comment by julienduchesne** [comment]
Let's get the resource merged first and then I'll review this one!

**Comment by justinTM** [comment]
API documentation was ever so slightly incorrect: https://github.com/grafana/grafana/pull/44743

**Comment by justinTM** [comment]
@julienduchesne 
- 404 error after creating library panel resource in test: https://drone.grafana.net/grafana/terraform-provider-grafana/632/4/3
- offending line of code: https://github.com/grafana/terraform-provider-grafana/pull/360/files#diff-29bd1683a4b9292a493f80b75e510bec62e5990201f473aeeaf759fb49868542R18

**Comment by julienduchesne** [comment]
To answer what you wrote here: https://github.com/grafana/terraform-provider-grafana/pull/354#issuecomment-1028532642

Yes, it should work. Terraform will figure out dependencies. However, the issue may be on Grafana's side and the panel is not immediately available after a write. If you can't get it to work I can take a look tomorrow

Let's keep the discussion here

**Comment by justinTM** [comment]
see https://github.com/grafana/terraform-provider-grafana/pull/370

**Pull request closed without merging**
