### PR TITLE
Adding Flux data source support for InfluxDB

### LINKED ISSUE #203: InfluxDB Flux support?
I can create Flux data source manually in Grafana UI.
However, when want to mange it via Terraform, it raises error.

I am following [InfluxDB 2.x for Flux example](https://grafana.com/docs/grafana/latest/datasources/influxdb/provision-influxdb/), trying to set
```
json_data {
  version = "Flux"
  organization = "any"
}

secure_json_data {
  token = "xxx"
}
```

**Expect**
data source is created successfully and have type InfluxDB using Flux language

**Actual**
An argument named "version" is not expected here
An argument named "organization" is not expected here
An argument named "token" is not expected here

### PR DESCRIPTION
**Pull request by stevenleadbeater**
Depends on https://github.com/grafana/grafana-api-golang-client/pull/60 being merged first and checksum file being updated with a new version
Fixes: https://github.com/grafana/terraform-provider-grafana/issues/203

### CODE REVIEW

**Comment by julienduchesne** [comment]
woops. I broke the version but bundling another change. Let me fix that in master @stevenleadbeater

**Comment by stevenleadbeater** [comment]
lol, I was fixing that too :+1:

**Comment by julienduchesne** [comment]
> lol, I was fixing that too 👍

Great, I'll merge your PR then 👍 . Thanks!

**Review by julienduchesne — APPROVED** [review]
LGTM! Thanks for your contribution!

**Comment by stevenleadbeater** [comment]
Thanks @julienduchesne :heart:

**Pull request merged**
