### PR TITLE
RBAC - Add new fields for managing grafana_role resource

### PR DESCRIPTION
**Pull request by vtorosyan**
Grafana RBAC API supports new fields which are going to be released with Grafana 9.0. This PR adds the support to the `grafana_role` resource, which allows to manage RBAC roles. 

Pre-requisite PR: https://github.com/grafana/grafana-api-golang-client/pull/78

Fixes - https://github.com/grafana/terraform-provider-grafana/issues/379

### CODE REVIEW

**Review by Jguer — APPROVED** [review]

**Comment by vtorosyan** [comment]
@julienduchesne @inkel I have updated to include a message which indicates the Grafana version since the fields are available. Note that I found out that the fields are out there since 8.5, so this should be safe to merge.

**Review by julienduchesne — COMMENTED** [review]
Please update the client: https://github.com/grafana/grafana-api-golang-client/releases/tag/v0.5.2

**Comment by julienduchesne** [comment]
One last thing. I don't have an enterprise setup. Can you boot up a Grafana 8.4 or lower and check that the tests still pass?

**Comment by vtorosyan** [comment]
I've just spotted an error that I made when updating Go client, here is a quick fix for that - https://github.com/grafana/grafana-api-golang-client/pull/85

Once the go client is merged, I will bump up the version in this PR and happy to merge - have run tests in enterprise and they passed with the right fixes - will obviously double check after library upgrade.

**Comment by vtorosyan** [comment]
@julienduchesne how can I release https://github.com/grafana/grafana-api-golang-client ? As I would need a new version with [this fix](https://github.com/grafana/grafana-api-golang-client/commit/96f0cae0daf1651ebd87a747a74b3e5b4700f502).

**Comment by julienduchesne** [comment]
> @julienduchesne how can I release https://github.com/grafana/grafana-api-golang-client ? As I would need a new version with [this fix](https://github.com/grafana/grafana-api-golang-client/commit/96f0cae0daf1651ebd87a747a74b3e5b4700f502).

https://github.com/grafana/grafana-api-golang-client/releases/tag/v0.7.0

**Pull request merged**
