### PR TITLE
Change of Library

### LINKED ISSUE #26: Upstream Library Ownership
Hi there,

I'm interested in adding additional functionality to this provider, and have hit a bit of a roadblock: it isn't clear who the maintaining party of the upstream library is.

From what I can gather, it appears that the library was changed in #16, and @apparentlymart voiced that [he's no longer able to maintain it](https://github.com/apparentlymart/go-grafana-api/pull/6#issuecomment-367135123). 
I haven't had any success reaching out to @teemupo who is the owner of the current fork, and judging by the fact that his [PR](https://github.com/apparentlymart/go-grafana-api/pull/7) remains open, I'd presume he doesn't have a strong interest in maintaining it either.

It appears to me that the upstream library is in need of a more permanent home, any ideas on what would be the best course of action here?

If no one else is in a position to do so, we'd like to offer to take ownership of the upstream library and maintain it, pulling back in contributions that have been made on other forks as well.

cc @sbower @msuterski @tonglil

### PR DESCRIPTION
**Pull request by mlclmj**
Hi!

Now that the library has been transferred to [nytm/go-grafana-api](https://github.com/nytm/go-grafana-api) and has been brought up to speed with the previously used repo, I have the following updates for the provider to finish this transition:

- Update the location of the go-grafana-api library from github.com/teemupo/go-grafana-api to github.com/nytm/go-grafana-api in the provider and resource files
- Update vendor.json file and update vendor dependencies to reflect library change

Closes #26

### CODE REVIEW

**Comment by pearkes** [comment]
@mlclmj do you plan on re-opening this? Was on my list to run acceptance tests and get it merged per the plan in #26. Let me know if you want to take a different route!

**Comment by mlclmj** [comment]
Hey @pearkes! 
I was just about to comment in #26 -- I closed this temporarily as we just came across https://github.com/grafana-tools/sdk, and we're thinking it may be a better alternative to maintaining an entirely separate client as it has more functionality and is semi-official. Any thoughts on which one you think would be a better option? I can most certainly reopen this PR if you'd prefer this route, I just wanted to hold off merging it until a course of action is decided on. Let me know your thoughts!

**Comment by pearkes** [comment]
@mlclmj without looking to closely it looks like they're still working on building it out based on the [status](https://github.com/grafana-tools/sdk#status-of-rest-api-realization-). I'd imagine it might take some work to move to.

It doesn't look like an extremely active library and without full coverage I'd be concerned it could impede work that people may want to do to this provider. If you maintain the SDK and have an ear to this community you may be in a position to support the provider better than the official SDK, though that is a little unintuitive. 😄

So I'd say given the information at hand we that this PR is the right approach for now. But I'm easy either way!

**Comment by mlclmj** [comment]
Hey @pearkes, sorry for the delay getting back to you on this- I'm in agreement with you here, I think the library we now maintain would be the best option. We tried to rouse the folk maintaining the SDK to see whether it'd be a viable possibility so that there aren't two being clients developed in parallel, however we have yet to have any luck and I agree that it'd likely block continued work on this provider.

I'm reopening this PR so that we can get this change finalized and continue development, thanks again for your help with this!

**Comment by tonglil** [comment]
Hey @pearkes, we're looking to roll the use of the new features @mlclmj worked on into our CI pipeline and it would be great if we don't have to build the binary :)

Any chance for a review?

**Comment by pearkes** [comment]
Tests and vendor changes look good to me! Merging this.

**Comment by pearkes** [comment]
@tonglil @mlclmj are you two interested in getting commit access to this repo? Would be great to get your help maintaining and improving it. I'd happily facilitate that. See some background here: https://www.terraform.io/docs/extend/community/contributing.html.

If so feel free to drop me an email: jack@hashicorp.com

**Pull request merged**
