### PR TITLE
Add missing contact point integrations

### PR DESCRIPTION
**Pull request by yuri-tceretian**
This PR adds 3 missing integrations:
- LINE https://github.com/grafana/alerting/blob/f5fde7b9a4b73e8687e50aedf78773981f9d7a11/receivers/line/config.go#L12-L16
- Webex https://github.com/grafana/alerting/blob/f5fde7b9a4b73e8687e50aedf78773981f9d7a11/receivers/webex/config.go#L19-L24

### CODE REVIEW

**Review by alexweav — APPROVED** [review]
LGTM

**Comment by julienduchesne** [comment]
Since there's a 10.2 feature in there, let's wait till it's released and there's a CI pipeline for it before merging

**Comment by yuri-tceretian** [comment]
@julienduchesne good point! I removed the oncall integration from this PR and will open a new one which we can keep open until the release.

**Review by julienduchesne — APPROVED** [review]
Perfect! :shipit:

**Pull request merged**
