### PR TITLE
Migrating to the terraform plugin SDK.

### PR DESCRIPTION
**Pull request by lazzurs**
Migrated the provider to the terraform plugin SDK using the automated
tool. Build works and passes tests.

### CODE REVIEW

**Comment by tonglil** [comment]
Hi @lazzurs , do you mind rerunning the migration tool once more?
Otherwise if you can post some info about it I can try running the migration.

Thanks!

Also, do you know if there is a deadline to migrating to the plugin SDK?

**Comment by lazzurs** [comment]
Hi,

No problem. I will get this updated shortly.

**Comment by mlclmj** [comment]
Looking at this [migration guide](https://www.terraform.io/docs/extend/plugin-sdk.html), I think we'll need to upgrade the version of go we're using as well.

**Comment by lazzurs** [comment]
Hey sorry for the wait, updated to the latest master so this will merge. Also updated to the latest plugin SDK version.

**Comment by trotttrotttrott** [comment]
Still want this, but unfortunately this got a bit stale. Will be attempting to go straight to SDK v2. Tracking in https://github.com/grafana/terraform-provider-grafana/issues/159.

**Pull request closed without merging**
