### PR TITLE
Update resource grafana_data_source

### LINKED ISSUE #22: expand json_data field usage.
Data sources have more that already defined json_data. Elasticsearch have own set of variables, tlsSkipVerify  also is not supported,

### LINKED ISSUE #42: Allow skipping TLS verify in datasources
Please add support for setting the `skip TLS verify` flag via the `grafana_data_source` resource for Prometheus datasources. Our test environment is using LE staging certificates which will cause Grafana to fail fetching data due to an untrusted certificate.

### Affected Resource(s)
Please list the resources as a list, for example:
- grafana_data_source

### PR DESCRIPTION
**Pull request by mlclmj**
## Summary
Makes long-overdue updates to the data source resource to introduce additional datasource types that can be fully configured with this provider including:
- Elasticsearch
- Graphite
- OpenTSDB
- Prometheus
- MySQL
- MSSQL
- Postgres

This change also adds better testing for the types of datasources that can be added.

## Details
- Updated the upstream library to [v0.3.1](https://github.com/nytm/go-grafana-api/releases/tag/v0.3.1)
- Reordered schema fields into alphabetical order for readability/maintainability
- Added table tests for the various data source types supported. Note that the Grafana API doesn't actually validate the presence of any of these fields or their values, however this is valuable in making sure that the upstream library is parsing and submitting values to Grafana as expected.
- As part of this work, the `access_key` and `secret_key` fields of the `secure_json_data` block are now marked as optional rather than required. Previously this was in place as the only datasource type using the `secret_json_data` block was Cloudwatch, though this is no longer the case. This shouldn't result in a breaking change for anyone configuring Cloudwatch datasources through this provider.
- Vendor folder was updated using `go mod vendor`

Resolves #22 
Resolves #42

### CODE REVIEW

**Comment by mlclmj** [comment]
Resolves #54

**Comment by mlclmj** [comment]
Resolves #68

**Review by tonglil — APPROVED** [review]
Nice set of changes, LGTM

**Comment by moseskt** [comment]
@mlclmj any eta for full support for configuring Azure Monitor via terraform?

**Pull request merged**
