### PR TITLE
Alerting: Add `details` field to pagerduty contact point

### PR DESCRIPTION
**Pull request by alexweav**
Grafana recently added a new `details` field to pagerduty in https://github.com/grafana/alerting/pull/65/files

Add it to the provider.

### CODE REVIEW

**Review by JohnnyQQQQ — APPROVED** [review]
LGTM

**Comment by bschaeffer** [comment]
Thank y'all for jumping on this!

**Comment by bschaeffer** [comment]
Probably closes https://github.com/grafana/terraform-provider-grafana/issues/911 when merged

**Review by inkel — APPROVED** [review]

**Comment by bschaeffer** [comment]
What are the odds this gets merged and officially release in the next week? Just wondering what the process is after merge so we can plan some work related.

**Comment by bschaeffer** [comment]
🎉 Thank y'all for getting this out so quickly!

**Pull request merged**
