### PR TITLE
[Fix] Adds check to ensure that the Grafana-Terraform-Provider header is set

### LINKED ISSUE #1630: [Fix] Returns an Error if the Grafana-Terraform-Provider Header is missing for Requests to the SLO API
To prevent regression due to missing headers from the Terraform Provider, we add a check directly in the TF Provider that ensures that `resourceSloRead` calls always have a `readOnly.Provenance` field of "terraform". 

`resourceSloRead` is called after all CREATE/UPDATEs made by the Terraform Provider, so it is reasonable to expect that the modified Slo would have a `readOnly.Provenance` field of `terraform`.

If this is missing, it's likely because the header was removed from within the Terraform Provider.

### PR DESCRIPTION
**Pull request by elainevuong**
To prevent regression due to missing request headers from the Terraform Provider, we add a check in the TF Provider Tests that ensures that following a successful CREATE or UPDATE, that a SLO returned from the READ call to the SLO API has a `provenance` field of `terraform`. 

This is **done directly in the TF Provider Tests** `resource_slo_test` and does **NOT** affect the actual function of the Terraform Provider, which means it does not interfere with IMPORT functionality.

Fixes #1630

### CODE REVIEW

**Comment by elainevuong** [comment]
error vid - missing the `Grafana Terraform Provider` header

https://github.com/grafana/terraform-provider-grafana/assets/73451363/9f161a85-8a8e-450e-afe3-f0765f0f4968

**Comment by elainevuong** [comment]
success vid

https://github.com/grafana/terraform-provider-grafana/assets/73451363/08bad5ee-269e-474d-bd02-2ed81d8ddedc

**Review by julienduchesne — COMMENTED** [review]
This prevents someone from importing a SLO and taking it over with Terraform

**Comment by ellisda** [comment]
> This prevents someone from importing a SLO and taking it over with Terraform

Is that because the `resourceSloRead` function is called during import as well? Is there a unit or integration test that we can add such a check to, outside of the production code path?

**Comment by julienduchesne** [comment]
Yep, read is called on imports. The only way to test this would be to have a new acceptance test that creates a SLO without the header and then imports it (plenty of import examples in other TF tests)

**Comment by elainevuong** [comment]
~~I'll update this - and add the test @julienduchesne suggested - a new acceptance test that creates a SLO without the header and then imports it. thanks for the comments!~~

ended up doing this check directly in the TF Provider Tests, and not in the Provider itself so it shouldn't affect the Import functionality. doing the import tests took a bit more time to think through - I think it would require changes to the TF SLO Schema, since we don't currently have the `readOnly` field included in our SLO Schema anywhere. decided to just test for the header directly in our TF Provider Tests instead

**Review by julienduchesne — APPROVED** [review]

**Pull request merged**
