### PR TITLE
Update dashboards with correct ForceNew on folder

### PR DESCRIPTION
**Pull request by ghmeier**
Updates https://github.com/terraform-providers/terraform-provider-grafana/pull/38 with the requested changes.

### CODE REVIEW

**Comment by wjam** [comment]
@appilon Is there any chance that this can be merged? It'll be a very useful feature!

**Comment by ttacon** [comment]
Hey folks, any update on if this PR will land or not? We'd love to be able to use this functionality. Cheers!

**Comment by nlamirault** [comment]
Hi, a new release embedding this feature would be welcome ! :)

**Comment by wjam** [comment]
@appilon @bflad Is there any chance of getting this merged?

**Comment by wjam** [comment]
@appilon @bflad @paultyng Any chance of getting this merged?

**Comment by wjam** [comment]
@appilon @bflad @paultyng Any chance of getting this merged?

**Comment by teddylear** [comment]
Please merge!

**Comment by BensamV** [comment]
Please merge!

**Comment by ghmeier** [comment]
Yay! Thanks @paultyng!

**Pull request merged**
