### PR TITLE
AccessControl: Add description in AccessControl resources docs

### LINKED ISSUE #209: AccessControl: Add description in Access Control resources docs
As pointed out by @trotttrotttrott, we need to add descriptions in docs for grafana_role, grafana_builtin_role_assignment.

### PR DESCRIPTION
**Pull request by gamab**
Add missing descriptions to accesscontrol resources fields in docs

Fixes #209

### CODE REVIEW

**Review by osg-grafana — APPROVED** [review]

**Comment by osg-grafana** [comment]
Looks like there is no backport labelling in this repo. Should this be backported to v8.0.x?

**Comment by osg-grafana** [comment]
What is the release milestone?

**Comment by gamab** [comment]
@trotttrotttrott seemed to tell us there is no formal releasing process for this.

**Comment by vtorosyan** [comment]
This is semi-official/best effort thing, we are not going to advise/suggest/communicate to customers to use terraform, unless they explicitly ask. In general the terraform release is not formal as far as I understand and is done manually as needed. We will look into the usage and needs more in the future.

**Review by trotttrotttrott — CHANGES_REQUESTED** [review]
The descriptions look good, but the descriptions should go in the actual schema in the Go code. Then you run `go generate` to generate the files in `docs/`. The [readme](https://github.com/grafana/terraform-provider-grafana#documentation) has a little more info. Look for the `Description` fields in the other resources for examples.

**Comment by gamab** [comment]
Thanks for pointing that out nicely :smile:

**Review by trotttrotttrott — APPROVED** [review]
Thanks @gamab!

**Pull request merged**
