### PR TITLE
:sparkles: Add of `disable_provenance` for grafana_contact_point

### PR DESCRIPTION
**Pull request by afreyermuth98**

### CODE REVIEW

**Comment by julienduchesne** [comment]
Tests are failing with 
```
Error: internal/resources/grafana/resource_alerting_contact_point_test.go:89:109: missing ',' before newline in argument list
```

**Comment by afreyermuth98** [comment]
Updated 😬

**Comment by julienduchesne** [comment]
> Updated 😬

Sorry, I merged some PRs today so you'll have to update your branch to fix the conflicts

**Comment by julienduchesne** [comment]
👋 Can you squash the commits. It's a bit hard to review as it is

**Comment by afreyermuth98** [comment]
Done :)

**Review by julienduchesne — APPROVED** [review]
Thanks!

**Pull request merged**
