### PR TITLE
add data_source_folders

### PR DESCRIPTION
**Pull request by justinTM**

### CODE REVIEW

**Comment by justinTM** [comment]
here's an example of what this feature should enable:

```terraform
// if dashboards are found in BA folders whose titles are not found in config.json,
// then they are consider "user-created" dashboards and would be overwritten if terraform
// re-deploys folders.
data "grafana_folders" "all" {
}

data "grafana_folder" "ba_in_title" {
  for_each = [ for title, uid in data.grafana_folders.all.folders :
    uid if length(regexall(".*BA.*", title)) > 0 ]
  
  uid = each.value
} 

data "grafana_dashboards" "in_ba_folders" {
  folder_ids = [ for folder in data.grafana_folder.ba_in_title : folder.id ]
}

// dashboards in folders "BA.*" whose titles aren't in this repo's provisioning/config.json file
data "grafana_dashboard" "user_created_in_ba_folders" {
  for_each = [ for dashboard in data.grafana_dashboards.in_ba_folders :
    dashboard if !contains(keys(local.some_or_all_dashboard_jsons), "${dashboard.folder}/${dashboard.title}") ]
  uid = each.value.uid
}

resource "local_file" "user_dashboards" {
  # write complete, rendered dashboard output JSON files to local directory
  for_each  = data.grafana_dashboard.user_created_in_ba_folders

  content   = each.value.config_json
  filename  = "${join("-", regexall("\\w+", each.value.folder))}/${join("-", regexall("\\w+", each.value.title))}.json"
}
```

**Comment by justinTM** [comment]
```console
Error: json: cannot unmarshal number -1 into Go struct field FolderDashboardSearchResponse.folderId of type uint
```

**Comment by justinTM** [comment]
i will convert uint `folderId` to some other type of int `int` or `int64` later, because [GrafanaCloud Billing/Usage dashboards contain a `folderId` of `-1`](https://github.com/grafana/grafana-api-golang-client/pull/62#issuecomment-1039853640) which currently results in the above JSON unmarshalling error.

**Comment by julienduchesne** [comment]
Implemented in https://github.com/grafana/terraform-provider-grafana/pull/583

**Pull request closed without merging**
