### PR TITLE
Add organization id to the provider.

### PR DESCRIPTION
**Pull request by medains**
Use the change in https://github.com/grafana/grafana-api-golang-client/pull/9 (previous submitted to https://github.com/nytm/go-grafana-api/pull/62) to
apply an organization id to the provider.

Usage might look like this:

```hcl
provider "grafana" {
  url = "someurl"
  auth = "adminuser:somepass"
}

resource "grafana_organization" "neworg" {
  name = "neworg"
  admin = "neworgadmin"
}

provider "grafana" {
  alias = "neworg"
  url = "someurl"
  auth = "neworgadmin:somepass"
  org_id = grafana_organization.neworg.org_id
}

resource "grafana_data_source" "neworg_graphite" {
  provider = grafana.neworg
  type = "graphite"
  name = "neworg-graphite"
}
```

Co-authored-by: hansnqyr <luke@nqyr.io>

This is obviously dependent on the go-grafana-api PR, and addresses the same issue that @bcampoli was addressing in https://github.com/terraform-providers/terraform-provider-grafana/pull/60

### CODE REVIEW

**Comment by trotttrotttrott** [comment]
@medains this looks great, but we've changed the provider to https://github.com/grafana/grafana-api-golang-client since you opened it. This is so we can have folks in the `grafana` org help with maintenance. Do you mind opening a PR on that repo? And then also rebasing master here?

**Comment by medains** [comment]
Will do, thanks.

**Comment by medains** [comment]
Updated, rebased and the PR opened on the new client repo.

**Comment by medains** [comment]
Updates, rebased and applied changes based on the now-accepted change to the client api

**Comment by qvistgaard** [comment]
Any chance for this to be merged in the near future?

**Comment by medains** [comment]
@trotttrotttrott - the api changes got merged a while ago, can we get this merged now?

**Comment by Merenon** [comment]
Yes, also very looking forward into this change being merged!

**Comment by medains** [comment]
Noticed when using this in anger that the schema TypeInt conversion to int64 for the api library needed a bit of work.

**Review by trotttrotttrott — APPROVED** [review]
Thanks @medains!

> Noticed when using this in anger that the schema TypeInt conversion to int64 for the api library needed a bit of work.

Could you elaborate on this?

**Comment by medains** [comment]
> Thanks @medains!
> 
> > Noticed when using this in anger that the schema TypeInt conversion to int64 for the api library needed a bit of work.
> 
> Could you elaborate on this?

Yes: 

> Thanks @medains!
> 
> > Noticed when using this in anger that the schema TypeInt conversion to int64 for the api library needed a bit of work.
> 
> Could you elaborate on this?

The previous code ```d.Get("org_id").(int64)``` gives an error something like "interface{} is type int not int64" - due to the "TypeInt" schema definition.  Since there's no "TypeInt64", this conversion is needed.
I found similar solutions to this issue in the aws provider, like here:
https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_ssm_maintenance_window.go#L85

**Pull request merged**
