### PR TITLE
adding "disableResolveMessage", "sendReminder" and "frequency"

### PR DESCRIPTION
**Pull request by quinont**
Adding "disableResolveMessage", "sendReminder" and "frequency" to alert
configuration.

### CODE REVIEW

**Review by mlclmj — COMMENTED** [review]
This looks good--do you mind updating the acceptance test + docs for these changes?

**Comment by quinont** [comment]
yes, I can do that... I'm working on it...

**Comment by quinont** [comment]
I'm sorry for the delayed response. can you check my pull request?

**Comment by AndrewPentsak** [comment]
Guys, can you merge this PR ?

**Comment by Puneeth-n** [comment]
Would be great if we could merge this

**Comment by julienduchesne** [comment]
These are supported. Thanks to https://github.com/grafana/terraform-provider-grafana/pull/145

**Pull request closed without merging**
