### PR TITLE
Update links to documentation

### PR DESCRIPTION
**Pull request by IevaVasiljeva**
Thanks to Vardan for pointing out that docs have moved!

### CODE REVIEW

**Review by vtorosyan — APPROVED** [review]
Thanks for fixing.

**Review by inkel — APPROVED** [review]
Thank you!

**Comment by inkel** [comment]
Note that you need to run `go generate` and commit&push the changes to the documentation.

**Comment by julienduchesne** [comment]
Force merged, failing tests are just flaky

**Pull request merged**
