### PR TITLE
Check for data source 404 in the correct place

### LINKED ISSUE #55: ReadDataSource fails if the data source is not there
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

`Terraform v0.11.13`

### Affected Resource(s)
- grafana_data_source

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource grafana_data_source "derp" {
  type = "cloudwatch"
  name = "DERP"

  json_data {
    assume_role_arn = "arn:aws:iam::123456789012:role/Derp"
    auth_type       = "arn"
    default_region  = "ap-southeast-2"
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

Terraform should nuke the data source from its state file.

### Actual Behavior
What actually happened?

Terraform exits with a "404 Not Found" error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

### PR DESCRIPTION
**Pull request by sjauld**
Fixes #55

### CODE REVIEW

**Comment by analytically** [comment]
@appilon would be cool if this could get merged :-)

**Comment by analytically** [comment]
@paultyng merge possible?

**Comment by jufemaiz** [comment]
Woo!

Wait, this isn't some sort of April Fool's thing is it?

**Comment by jufemaiz** [comment]
Is @terraform-providers maintaining this much?

**Comment by sjauld** [comment]
I believe that most of the minor providers on terraform-providers are unmaintained by Hashicorp. The approach is "certify and walk away".

**Review by paultyng — APPROVED** [review]

**Comment by paultyng** [comment]
@sjauld is correct, we don't maintain many of the providers in the `terraform-providers` org, they are maintained by community members and the companies themselves for the most part.

**Pull request merged**
